### PR TITLE
RBMHUIM-2509: C#: get form submission

### PR DESCRIPTION
**Pull request by mteufner**

### CODE REVIEW

**Comment by pablotp** [comment]
I'm having some troubles building the docker image.
@mteufner  @PatrickSchuster  did you also have problems with the csharp image?
Screenshot 2020-07-29 at 12 55 54

**Comment by mteufner** [comment]
@pablotp Try executing it inside the UimCsharpExamples directory.

**Comment by pablotp** [comment]
Unfortunately, I does not help :-(
I've even executed `docker system prune` but I'm still getting the same error:
Screenshot 2020-07-29 at 14 44 21

**Comment by mteufner** [comment]
Which branch are you trying to build. This should actually work :/

**Comment by pablotp** [comment]
> Which branch are you trying to build. This should actually work :/
> Stupid question: You ran the dotnet publish command before right?

That was my issue. I overlooked that you need to install dotnet before running the docker command.
I would suggest to add a step in the readme to install dotnet (https://dotnet.microsoft.com/download) or to install dotnet in the container.

**Pull request merged**
