### PR TITLE
First try to fix

### PR DESCRIPTION
**Pull request by pablotp**

### CODE REVIEW

**Comment by florentinRB** [comment]
It works for me locally. We just need this branch as mine would now have merge conflicts.
But I´m not able to build the docker image anymore. Can you try it yourself?

```
Sending build context to Docker daemon  14.69MB
Step 1/5 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1
 ---> 052ed32b57d8
Step 2/5 : COPY * /App/
 ---> Using cache
 ---> 4cba80425665
Step 3/5 : RUN cd /App && dotnet publish -c Release
 ---> Running in f2be6863e314
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /App/UimCsharpExamples.csproj (in 1.14 sec).
Release/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [/App/UimCsharpExamples.csproj]
Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [/App/UimCsharpExamples.csproj]
obj/Release/netcoreapp3.1/UimCsharpExamples.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [/App/UimCsharpExamples.csproj]
The command '/bin/sh -c cd /App && dotnet publish -c Release' returned a non-zero code: 1
```

**Comment by mteufner** [comment]
> But I´m not able to build the docker image anymore. Can you try it yourself?

For me it worked after I deleted all the created files in the bin and obj folder.

**Comment by florentinRB** [comment]
> For me it worked after I deleted all the created files in the bin and obj folder.

Thanks, that´s the missing thing to work

**Comment by florentinRB** [comment]
In the custom-notification-verification it basically works without all the parameters described in the readme.
`docker run -it --rm -e "EXAMPLE=custom-notification-verification" <DOCKER_IMAGE_NAME>`
Should we notice that in the readme or not?

**Comment by pablotp** [comment]
> In the custom-notification-verification it basically works without all the parameters described in the readme.
> `docker run -it --rm -e "EXAMPLE=custom-notification-verification" <DOCKER_IMAGE_NAME>`
> Should we notice that in the readme or not?

How do you suggest we write this in the README?

**Comment by pablotp** [comment]
@florentinRB btw, please do not merge this PR as it was intended only to look for a solution to your issue. I'd suggest to cherry-pick the changes into your branch/PR and then close this.

**Comment by florentinRB** [comment]
> How do you suggest we write this in the README?
like this

**Pull request closed without merging**
